In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("Employee Salaries Datatset.csv")
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.20, random_state=0)


In [2]:
# Normalisasi
from sklearn.preprocessing import MinMaxScaler

X_train = MinMaxScaler().fit_transform(X_train)
X_test = MinMaxScaler().fit_transform(X_test)

In [3]:
print(X_test)

[[0.17897538 1.         0.28571429]
 [0.24683965 0.         0.65306122]
 [0.22222222 0.         0.69387755]
 [0.11510313 1.         0.42857143]
 [0.06852961 0.         0.10204082]
 [0.75382568 0.         0.65306122]
 [0.85362608 1.         0.87755102]
 [1.         1.         1.        ]
 [0.54757152 0.         0.55102041]
 [0.11244178 1.         0.08163265]
 [0.22022621 0.         0.        ]
 [0.33466401 1.         0.67346939]
 [0.         1.         0.30612245]
 [0.00864937 1.         0.12244898]
 [0.19560878 0.         0.16326531]
 [0.65402528 0.         0.46938776]
 [0.32135729 0.         0.7755102 ]
 [0.05189621 0.         0.10204082]
 [0.22155689 1.         0.16326531]
 [0.82035928 1.         0.44897959]]


In [4]:
# clasifikasi dengan neural network 
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)

clf.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=3, learning_rate_init=0.1, max_iter=100)

In [5]:
y_pred = clf.predict(X_test)

In [6]:
from sklearn.metrics import accuracy_score

round(accuracy_score(y_test,y_pred),3)

0.8